CREATE OR REPLACE FUNCTION "public"."system_06011001"("v_cod" int4,
                                                    "v_ctg_tpr_id" varchar,
                                                    "v_ctg_tpr_desc" varchar,
                                                    "v_ctg_tpr_obs" text,
                                                    "v_ctg_tpr_expe_loc" varchar,
                                                    "v_ctg_tpr_resu_loc" varchar,
                                                    "v_ctg_tpr_dpre" int,
                                                    "v_ctg_tpr_email" varchar,
                                                    "v_ctg_tpr_coradm" int,
                                                    "v_ctg_tpr_cuopat" numeric,
                                                    "v_ctg_tpr_cuoemp" numeric,
                                                    "v_ctg_tpr_cuofun" numeric,
                                                    "v_ctg_tpr_cuoper" numeric,
                                                    "v_ctg_tpr_validez" int,
                                                    "v_ctg_tpr_poder" int,
                                                    "v_ctg_tpr_emp" int,
                                                    "v_ctg_tpr_image" varchar,
                                                    "v_ctg_tpr_uso" int,
                                                    "v_ctg_tpr_on" int,
                                                    "v_ctg_tpr_req_fab" int,
                                                    "v_ctg_tpr_req_fabadi" int,
                                                    "v_ctg_tpr_req_fabpriact" int,
                                                    "v_ctg_tpr_req_fabprofin" int,
                                                    "v_ctg_tpr_req_fabmatpri" int,
                                                    "v_ctg_tpr_req_fabenv" int,
                                                    "v_ctg_tpr_req_fabenvadi" int,
                                                    "v_ctg_tpr_req_prop" int,
                                                    "v_ctg_tpr_req_repr" int,
                                                    "v_ctg_tpr_req_imp" int,
                                                    "v_ctg_tpr_req_alm" int,
                                                    "v_ctg_tpr_req_dist" int,
                                                    "v_ctg_tpr_req_formula" int,
                                                    "v_ctg_tpr_req_sec" int,
                                                    "v_ctg_tpr_req_titular" int,
                                                    "v_ctg_tpr_req_acon" int,
                                                    "v_ctg_tpr_req_asq" int,
                                                    "v_ctg_tpr_req_dci" int,
                                                    "v_ctg_tpr_size" int,
                                                    "v_ctg_tpr_req_pesc" int,
                                                    "v_ctg_tpr_req_penc" int,
                                                    "v_ctg_tpr_req_mon" int,
                                                    "v_ctg_tpr_req_ins" int,
                                                    "v_ctg_tpr_req_val" int,
                                                    "v_ctg_tpr_req_abo" int,
                                                    "v_ctg_tpr_req_enva" int,
                                                    "v_ctg_tpr_email1" varchar,
                                                    "v_ctg_tpr_email2" varchar,
                                                    "v_ctg_tpr_email3" varchar,
                                                    "v_ctg_tpr_email4" varchar,
                                                    "v_ctg_tpr_vus_nusolemp" int,
                                                    "v_ctg_tpr_vus_nusolpat" int,
                                                    "v_ctg_tpr_vus_newing" int,
                                                    "v_ctg_tpr_req_remi" int,
                                                    "v_ctg_tpr_desc_email" text,
                                                    "v_ctg_tpr_sig1" varchar,
                                                    "v_ctg_tpr_sig2" varchar,
                                                    "v_ctg_tpr_sig3" varchar,
                                                    "v_ctg_tpr_sig4" varchar,
                                                    "v_ctg_tpr_sig5" varchar,
                                                    "v_ctg_tpr_correg" int,
                                                    "v_ctg_tpr_numimg" int,
                                                    "v_ctg_tpr_sta" char,
                                                    "v_ctg_tpr_usr" varchar,
                                                    "v_ctg_tpr_dt" date,
                                                    "v_ctg_id" int
                                                            )
  RETURNS "pg_catalog"."void" AS $BODY$
    BEGIN

		IF v_cod = 1 THEN
			INSERT 
            INTO ctg_tipo_productos(ctg_tpr_id,
                                    ctg_tpr_desc,
                                    ctg_tpr_obs,
                                    ctg_tpr_expe_loc,
                                    ctg_tpr_resu_loc,
                                    ctg_tpr_dpre,
                                    ctg_tpr_email,
                                    ctg_tpr_coradm,
                                    ctg_tpr_cuopat,
                                    ctg_tpr_cuoemp,
                                    ctg_tpr_cuofun,
                                    ctg_tpr_cuoper,
                                    ctg_tpr_validez,
                                    ctg_tpr_poder,
                                    ctg_tpr_emp,
                                    ctg_tpr_image,
                                    ctg_tpr_uso,
                                    ctg_tpr_on,
                                    ctg_tpr_req_fab,
                                    ctg_tpr_req_fabadi,
                                    ctg_tpr_req_fabpriact,
                                    ctg_tpr_req_fabprofin,
                                    ctg_tpr_req_fabmatpri,
                                    ctg_tpr_req_fabenv,
                                    ctg_tpr_req_fabenvadi,
                                    ctg_tpr_req_prop,
                                    ctg_tpr_req_repr,
                                    ctg_tpr_req_imp,
                                    ctg_tpr_req_alm,
                                    ctg_tpr_req_dist,
                                    ctg_tpr_req_formula,
                                    ctg_tpr_req_sec,
                                    ctg_tpr_req_titular,
                                    ctg_tpr_req_acon,
                                    ctg_tpr_req_asq,
                                    ctg_tpr_req_dci,
                                    ctg_tpr_size,
                                    ctg_tpr_req_pesc,
                                    ctg_tpr_req_penc,
                                    ctg_tpr_req_mon,
                                    ctg_tpr_req_ins,
                                    ctg_tpr_req_val,
                                    ctg_tpr_req_abo,
                                    ctg_tpr_req_enva,
                                    ctg_tpr_email1,
                                    ctg_tpr_email2,
                                    ctg_tpr_email3,
                                    ctg_tpr_email4,
                                    ctg_tpr_vus_nusolemp,
                                    ctg_tpr_vus_nusolpat,
                                    ctg_tpr_vus_newing,
                                    ctg_tpr_req_remi,
                                    ctg_tpr_desc_email,
                                    ctg_tpr_sig1,
                                    ctg_tpr_sig2,
                                    ctg_tpr_sig3,
                                    ctg_tpr_sig4,
                                    ctg_tpr_sig5,
                                    ctg_tpr_correg,
                                    ctg_tpr_numimg,
                                    ctg_tpr_sta,
                                    ctg_tpr_usr,
                                    ctg_tpr_dt,
                                    ctg_id

                                        )
                VALUES(v_ctg_tpr_id,
                        v_ctg_tpr_desc,
                        v_ctg_tpr_obs,
                        v_ctg_tpr_expe_loc,
                        v_ctg_tpr_resu_loc,
                        v_ctg_tpr_dpre,
                        v_ctg_tpr_email,
                        v_ctg_tpr_coradm,
                        v_ctg_tpr_cuopat,
                        v_ctg_tpr_cuoemp,
                        v_ctg_tpr_cuofun,
                        v_ctg_tpr_cuoper,
                        v_ctg_tpr_validez,
                        v_ctg_tpr_poder,
                        v_ctg_tpr_emp,
                        v_ctg_tpr_image,
                        v_ctg_tpr_uso,
                        v_ctg_tpr_on,
                        v_ctg_tpr_req_fab,
                        v_ctg_tpr_req_fabadi,
                        v_ctg_tpr_req_fabpriact,
                        v_ctg_tpr_req_fabprofin,
                        v_ctg_tpr_req_fabmatpri,
                        v_ctg_tpr_req_fabenv,
                        v_ctg_tpr_req_fabenvadi,
                        v_ctg_tpr_req_prop,
                        v_ctg_tpr_req_repr,
                        v_ctg_tpr_req_imp,
                        v_ctg_tpr_req_alm,
                        v_ctg_tpr_req_dist,
                        v_ctg_tpr_req_formula,
                        v_ctg_tpr_req_sec,
                        v_ctg_tpr_req_titular,
                        v_ctg_tpr_req_acon,
                        v_ctg_tpr_req_asq,
                        v_ctg_tpr_req_dci,
                        v_ctg_tpr_size,
                        v_ctg_tpr_req_pesc,
                        v_ctg_tpr_req_penc,
                        v_ctg_tpr_req_mon,
                        v_ctg_tpr_req_ins,
                        v_ctg_tpr_req_val,
                        v_ctg_tpr_req_abo,
                        v_ctg_tpr_req_enva,
                        v_ctg_tpr_email1,
                        v_ctg_tpr_email2,
                        v_ctg_tpr_email3,
                        v_ctg_tpr_email4,
                        v_ctg_tpr_vus_nusolemp,
                        v_ctg_tpr_vus_nusolpat,
                        v_ctg_tpr_vus_newing,
                        v_ctg_tpr_req_remi,
                        v_ctg_tpr_desc_email,
                        v_ctg_tpr_sig1,
                        v_ctg_tpr_sig2,
                        v_ctg_tpr_sig3,
                        v_ctg_tpr_sig4,
                        v_ctg_tpr_sig5,
                        v_ctg_tpr_correg,
                        v_ctg_tpr_numimg,
                        v_ctg_tpr_sta,
                        v_ctg_tpr_usr,
                        v_ctg_tpr_dt,
                        v_ctg_id
                        );
		END IF;
		
		IF v_cod = 2 THEN
			UPDATE 
				ctg_tipo_productos 
			SET
                ctg_tpr_id = v_ctg_tpr_id ,
                ctg_tpr_desc = v_ctg_tpr_desc ,
                ctg_tpr_obs = v_ctg_tpr_obs ,
                ctg_tpr_expe_loc = v_ctg_tpr_expe_loc ,
                ctg_tpr_resu_loc = v_ctg_tpr_resu_loc ,
                ctg_tpr_dpre = v_ctg_tpr_dpre ,
                ctg_tpr_email = v_ctg_tpr_email ,
                ctg_tpr_coradm = v_ctg_tpr_coradm ,
                ctg_tpr_cuopat = v_ctg_tpr_cuopat ,
                ctg_tpr_cuoemp = v_ctg_tpr_cuoemp ,
                ctg_tpr_cuofun = v_ctg_tpr_cuofun ,
                ctg_tpr_cuoper = v_ctg_tpr_cuoper ,
                ctg_tpr_validez = v_ctg_tpr_validez ,
                ctg_tpr_poder = v_ctg_tpr_poder ,
                ctg_tpr_emp = v_ctg_tpr_emp ,
                ctg_tpr_image = v_ctg_tpr_image ,
                ctg_tpr_uso = v_ctg_tpr_uso ,
                ctg_tpr_on = v_ctg_tpr_on ,
                ctg_tpr_req_fab = v_ctg_tpr_req_fab ,
                ctg_tpr_req_fabadi = v_ctg_tpr_req_fabadi ,
                ctg_tpr_req_fabpriact = v_ctg_tpr_req_fabpriact ,
                ctg_tpr_req_fabprofin = v_ctg_tpr_req_fabprofin ,
                ctg_tpr_req_fabmatpri = v_ctg_tpr_req_fabmatpri ,
                ctg_tpr_req_fabenv = v_ctg_tpr_req_fabenv ,
                ctg_tpr_req_fabenvadi = v_ctg_tpr_req_fabenvadi ,
                ctg_tpr_req_prop = v_ctg_tpr_req_prop ,
                ctg_tpr_req_repr = v_ctg_tpr_req_repr ,
                ctg_tpr_req_imp = v_ctg_tpr_req_imp ,
                ctg_tpr_req_alm = v_ctg_tpr_req_alm ,
                ctg_tpr_req_dist = v_ctg_tpr_req_dist ,
                ctg_tpr_req_formula = v_ctg_tpr_req_formula ,
                ctg_tpr_req_sec = v_ctg_tpr_req_sec ,
                ctg_tpr_req_titular = v_ctg_tpr_req_titular ,
                ctg_tpr_req_acon = v_ctg_tpr_req_acon ,
                ctg_tpr_req_asq = v_ctg_tpr_req_asq ,
                ctg_tpr_req_dci = v_ctg_tpr_req_dci ,
                ctg_tpr_size = v_ctg_tpr_size ,
                ctg_tpr_req_pesc = v_ctg_tpr_req_pesc ,
                ctg_tpr_req_penc = v_ctg_tpr_req_penc ,
                ctg_tpr_req_mon = v_ctg_tpr_req_mon ,
                ctg_tpr_req_ins = v_ctg_tpr_req_ins ,
                ctg_tpr_req_val = v_ctg_tpr_req_val ,
                ctg_tpr_req_abo = v_ctg_tpr_req_abo ,
                ctg_tpr_req_enva = v_ctg_tpr_req_enva ,
                ctg_tpr_email1 = v_ctg_tpr_email1 ,
                ctg_tpr_email2 = v_ctg_tpr_email2 ,
                ctg_tpr_email3 = v_ctg_tpr_email3 ,
                ctg_tpr_email4 = v_ctg_tpr_email4 ,
                ctg_tpr_vus_nusolemp = v_ctg_tpr_vus_nusolemp ,
                ctg_tpr_vus_nusolpat = v_ctg_tpr_vus_nusolpat ,
                ctg_tpr_vus_newing = v_ctg_tpr_vus_newing ,
                ctg_tpr_req_remi = v_ctg_tpr_req_remi ,
                ctg_tpr_desc_email = v_ctg_tpr_desc_email ,
                ctg_tpr_sig1 = v_ctg_tpr_sig1 ,
                ctg_tpr_sig2 = v_ctg_tpr_sig2 ,
                ctg_tpr_sig3 = v_ctg_tpr_sig3 ,
                ctg_tpr_sig4 = v_ctg_tpr_sig4 ,
                ctg_tpr_sig5 = v_ctg_tpr_sig5 ,
                ctg_tpr_correg = v_ctg_tpr_correg ,
                ctg_tpr_numimg = v_ctg_tpr_numimg ,
                ctg_tpr_sta = v_ctg_tpr_sta ,
                ctg_tpr_usr = v_ctg_tpr_usr ,
                ctg_tpr_dt = v_ctg_tpr_dt ,
                ctg_id = v_ctg_id
                
			WHERE 
				ctg_id = v_ctg_id;
		END IF;
		
		IF v_cod = 3 THEN
		  DELETE FROM ctg_tipo_productos 
			WHERE ctg_id = v_ctg_id ;
		END IF;
		
 END;
    $BODY$
  LANGUAGE plpgsql VOLATILE
  COST 1000